### ISSUE TITLE
Requesting a question that doesn't exist causes a 500 error

### ISSUE THREAD

**Issue by bitplane** [bitplane/technical-test-internal#6]
As per API spec this should be a 404 error.

Example:
    GET /question/9999

**Comment by bitplane** [comment]
```
TypeError: Cannot read property 'upvotes' of undefined
    at hideVotes (/home/gaz/code/technical-test-internal/lib/q-and-a.js:102:22)
    at Object.handler (/home/gaz/code/technical-test-internal/lib/q-and-a.js:36:19)
    at Object.handle (/home/gaz/code/technical-test-internal/lib/routing.js:43:19)
    at route (/home/gaz/code/technical-test-internal/lib/routing.js:57:30)
    at IncomingMessage.<anonymous> (/home/gaz/code/technical-test-internal/server.js:25:20)
    at emitNone (events.js:67:13)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at nextTickCallbackWith2Args (node.js:478:9)
    at process._tickCallback (node.js:392:17)
```
